export const SWITCH_IT_LOGO_SRC = "/branding/switch-it-logo.png";

/** Intrinsic size of the transparent lockup (not the old square canvas). */
export const SWITCH_IT_LOGO_WIDTH = 1106;
export const SWITCH_IT_LOGO_HEIGHT = 342;

/**
 * Transparent standalone Switch It symbol for launch / splash only.
 * Generated by scripts/generate-native-splash.mjs — no app-icon tile, no wordmark.
 */
export const SWITCH_IT_LAUNCH_MARK_SRC = "/branding/switch-it-launch-mark.png";
/** Intrinsic mark size after tile removal (see generate-native-splash). */
export const SWITCH_IT_LAUNCH_MARK_WIDTH = 201;
export const SWITCH_IT_LAUNCH_MARK_HEIGHT = 228;

/** Fraction of the shorter viewport side used for launch mark sizing (~25–30%). */
export const SWITCH_IT_LAUNCH_MARK_RATIO = 0.28;

export function containedLogoSize(
  maxWidth: number,
  maxHeight: number,
): { width: number; height: number } {
  const aspect = SWITCH_IT_LOGO_WIDTH / SWITCH_IT_LOGO_HEIGHT;
  let width = Math.max(1, Math.round(maxWidth));
  let height = Math.max(1, Math.round(maxWidth / aspect));
  if (height > maxHeight) {
    height = Math.max(1, Math.round(maxHeight));
    width = Math.max(1, Math.round(maxHeight * aspect));
  }
  return { width, height };
}

export function launchMarkCssPx(cssWidth: number, cssHeight: number): number {
  return Math.round(Math.min(cssWidth, cssHeight) * SWITCH_IT_LAUNCH_MARK_RATIO);
}

export function launchMarkContainSize(
  cssWidth: number,
  cssHeight: number,
): { width: number; height: number } {
  const max = launchMarkCssPx(cssWidth, cssHeight);
  const aspect = SWITCH_IT_LAUNCH_MARK_WIDTH / SWITCH_IT_LAUNCH_MARK_HEIGHT;
  let width = max;
  let height = Math.round(max / aspect);
  if (height > max) {
    height = max;
    width = Math.round(max * aspect);
  }
  return { width, height };
}
