export const SWITCH_IT_LOGO_SRC = "/branding/switch-it-logo.png";

/** Intrinsic size of the transparent lockup (not the old square canvas). */
export const SWITCH_IT_LOGO_WIDTH = 1106;
export const SWITCH_IT_LOGO_HEIGHT = 342;

/**
 * Square app-icon tile for launch / boot splash (mark only, no wordmark).
 * Generated by scripts/generate-native-splash.mjs from the same mark as AppIcon.
 */
export const SWITCH_IT_LAUNCH_ICON_SRC = "/branding/switch-it-launch-icon.png";
export const SWITCH_IT_LAUNCH_ICON_WIDTH = 512;
export const SWITCH_IT_LAUNCH_ICON_HEIGHT = 512;

/** Fraction of the shorter viewport side used for launch icon sizing (~28–32%). */
export const SWITCH_IT_LAUNCH_ICON_RATIO = 0.3;

export function containedLogoSize(
  maxWidth: number,
  maxHeight: number,
): { width: number; height: number } {
  const aspect = SWITCH_IT_LOGO_WIDTH / SWITCH_IT_LOGO_HEIGHT;
  let width = Math.max(1, Math.round(maxWidth));
  let height = Math.max(1, Math.round(maxWidth / aspect));
  if (height > maxHeight) {
    height = Math.max(1, Math.round(maxHeight));
    width = Math.max(1, Math.round(maxHeight * aspect));
  }
  return { width, height };
}

export function launchIconCssPx(cssWidth: number, cssHeight: number): number {
  return Math.round(Math.min(cssWidth, cssHeight) * SWITCH_IT_LAUNCH_ICON_RATIO);
}
