/**
 * Local MVP vehicle catalog for Israel-common manufacturers and models.
 *
 * Stored `vehicle_make` / `vehicle_model` values should use `name` strings
 * exactly when a confident match exists. `class` is an internal silhouette
 * taxonomy (not shown in the form) and matches existing illustration assets:
 * mini, hatchback, sedan, suv, pickup, van, other.
 *
 * Crossovers map to suv; wagons/coupes map to sedan; convertibles/sports to other.
 */
import type { VehicleType } from "@/lib/vehicle/types";

export type VehicleCatalogModel = {
  name: string;
  class: VehicleType;
};

export type VehicleCatalogMake = {
  name: string;
  aliases?: readonly string[];
  models: readonly VehicleCatalogModel[];
};

function m(name: string, vehicleClass: VehicleType): VehicleCatalogModel {
  return { name, class: vehicleClass };
}

export const VEHICLE_CATALOG: readonly VehicleCatalogMake[] = [
  {
    name: "Audi",
    models: [
      m("A1", "hatchback"),
      m("A3", "hatchback"),
      m("A4", "sedan"),
      m("A5", "sedan"),
      m("A6", "sedan"),
      m("A7", "sedan"),
      m("A8", "sedan"),
      m("Q2", "suv"),
      m("Q3", "suv"),
      m("Q5", "suv"),
      m("Q7", "suv"),
      m("Q8", "suv"),
      m("Q4 e-tron", "suv"),
      m("Q6 e-tron", "suv"),
      m("e-tron", "suv"),
      m("e-tron GT", "sedan"),
      m("TT", "other"),
    ],
  },
  {
    name: "BMW",
    aliases: ["bmw"],
    models: [
      m("1 Series", "hatchback"),
      m("2 Series", "sedan"),
      m("3 Series", "sedan"),
      m("4 Series", "sedan"),
      m("5 Series", "sedan"),
      m("7 Series", "sedan"),
      m("X1", "suv"),
      m("X2", "suv"),
      m("X3", "suv"),
      m("X4", "suv"),
      m("X5", "suv"),
      m("X6", "suv"),
      m("X7", "suv"),
      m("i4", "sedan"),
      m("i5", "sedan"),
      m("i7", "sedan"),
      m("iX", "suv"),
      m("iX1", "suv"),
      m("iX3", "suv"),
      m("XM", "suv"),
    ],
  },
  {
    name: "BYD",
    models: [
      m("Atto 2", "suv"),
      m("Atto 3", "suv"),
      m("Dolphin", "hatchback"),
      m("Han", "sedan"),
      m("Seal", "sedan"),
      m("Seal U", "suv"),
      m("Sealion 7", "suv"),
      m("Tang", "suv"),
    ],
  },
  {
    name: "Chevrolet",
    aliases: ["chevy"],
    models: [
      m("Aveo", "sedan"),
      m("Camaro", "other"),
      m("Captiva", "suv"),
      m("Cruze", "sedan"),
      m("Equinox", "suv"),
      m("Orlando", "van"),
      m("Spark", "mini"),
      m("Traverse", "suv"),
      m("Trax", "suv"),
    ],
  },
  {
    name: "Citroen",
    aliases: ["citroën", "citroen"],
    models: [
      m("Berlingo", "van"),
      m("C1", "mini"),
      m("C3", "hatchback"),
      m("C3 Aircross", "suv"),
      m("C4", "hatchback"),
      m("C4 Cactus", "suv"),
      m("C4 X", "sedan"),
      m("C5 Aircross", "suv"),
      m("C5 X", "sedan"),
    ],
  },
  {
    name: "Cupra",
    models: [
      m("Ateca", "suv"),
      m("Born", "hatchback"),
      m("Formentor", "suv"),
      m("Leon", "hatchback"),
      m("Tavascan", "suv"),
      m("Terramar", "suv"),
    ],
  },
  {
    name: "Dacia",
    models: [
      m("Duster", "suv"),
      m("Jogger", "hatchback"),
      m("Logan", "sedan"),
      m("Lodgy", "van"),
      m("Sandero", "hatchback"),
      m("Spring", "mini"),
    ],
  },
  {
    name: "Fiat",
    models: [
      m("500", "mini"),
      m("500e", "mini"),
      m("500X", "suv"),
      m("Doblo", "van"),
      m("Ducato", "van"),
      m("Panda", "mini"),
      m("Punto", "hatchback"),
      m("Tipo", "sedan"),
    ],
  },
  {
    name: "Ford",
    models: [
      m("EcoSport", "suv"),
      m("Explorer", "suv"),
      m("Fiesta", "hatchback"),
      m("Focus", "hatchback"),
      m("Kuga", "suv"),
      m("Mach-E", "suv"),
      m("Mondeo", "sedan"),
      m("Mustang", "other"),
      m("Puma", "suv"),
      m("Ranger", "pickup"),
      m("Transit", "van"),
    ],
  },
  {
    name: "Geely",
    models: [
      m("Coolray", "suv"),
      m("EX5", "suv"),
      m("Geometry C", "suv"),
      m("Okavango", "suv"),
      m("Starray", "suv"),
    ],
  },
  {
    name: "Honda",
    models: [
      m("Accord", "sedan"),
      m("Civic", "hatchback"),
      m("City", "sedan"),
      m("CR-V", "suv"),
      m("e:Ny1", "suv"),
      m("HR-V", "suv"),
      m("Jazz", "hatchback"),
    ],
  },
  {
    name: "Hyundai",
    models: [
      m("Accent", "sedan"),
      m("Elantra", "sedan"),
      m("Getz", "hatchback"),
      m("i10", "mini"),
      m("i20", "hatchback"),
      m("i30", "hatchback"),
      m("i35", "sedan"),
      m("Ioniq", "hatchback"),
      m("Ioniq 5", "suv"),
      m("Ioniq 6", "sedan"),
      m("Kona", "suv"),
      m("Palisade", "suv"),
      m("Santa Fe", "suv"),
      m("Tucson", "suv"),
      m("Venue", "suv"),
    ],
  },
  {
    name: "Kia",
    models: [
      m("Carnival", "van"),
      m("Ceed", "hatchback"),
      m("EV6", "suv"),
      m("EV9", "suv"),
      m("Niro", "suv"),
      m("Optima", "sedan"),
      m("Picanto", "hatchback"),
      m("Rio", "hatchback"),
      m("Seltos", "suv"),
      m("Sorento", "suv"),
      m("Soul", "suv"),
      m("Sportage", "suv"),
      m("Stonic", "suv"),
      m("Telluride", "suv"),
      m("XCeed", "suv"),
    ],
  },
  {
    name: "Lexus",
    models: [
      m("ES", "sedan"),
      m("IS", "sedan"),
      m("LBX", "suv"),
      m("LS", "sedan"),
      m("LX", "suv"),
      m("NX", "suv"),
      m("RX", "suv"),
      m("RZ", "suv"),
      m("UX", "suv"),
      m("UX 300e", "suv"),
    ],
  },
  {
    name: "MG",
    models: [
      m("HS", "suv"),
      m("Marvel R", "suv"),
      m("MG3", "hatchback"),
      m("MG4", "hatchback"),
      m("MG5", "sedan"),
      m("ZS", "suv"),
    ],
  },
  {
    name: "Mazda",
    models: [
      m("2", "hatchback"),
      m("3", "hatchback"),
      m("6", "sedan"),
      m("CX-3", "suv"),
      m("CX-30", "suv"),
      m("CX-5", "suv"),
      m("CX-60", "suv"),
      m("CX-90", "suv"),
      m("MX-5", "other"),
    ],
  },
  {
    name: "Mercedes-Benz",
    aliases: ["mercedes", "mercedes benz", "mercedes-benz", "merc"],
    models: [
      m("A-Class", "hatchback"),
      m("B-Class", "hatchback"),
      m("C-Class", "sedan"),
      m("CLA", "sedan"),
      m("CLE", "sedan"),
      m("CLS", "sedan"),
      m("E-Class", "sedan"),
      m("EQA", "suv"),
      m("EQB", "suv"),
      m("EQC", "suv"),
      m("EQE", "sedan"),
      m("EQS", "sedan"),
      m("G-Class", "suv"),
      m("GLA", "suv"),
      m("GLB", "suv"),
      m("GLC", "suv"),
      m("GLE", "suv"),
      m("GLS", "suv"),
      m("S-Class", "sedan"),
      m("Sprinter", "van"),
      m("Vito", "van"),
    ],
  },
  {
    name: "Mitsubishi",
    models: [
      m("ASX", "suv"),
      m("Attrage", "sedan"),
      m("Colt", "hatchback"),
      m("Eclipse Cross", "suv"),
      m("L200", "pickup"),
      m("Lancer", "sedan"),
      m("Outlander", "suv"),
      m("Pajero", "suv"),
      m("Space Star", "mini"),
    ],
  },
  {
    name: "Nissan",
    models: [
      m("Ariya", "suv"),
      m("Juke", "suv"),
      m("Leaf", "hatchback"),
      m("Micra", "mini"),
      m("Navara", "pickup"),
      m("Note", "hatchback"),
      m("Pulsar", "hatchback"),
      m("Qashqai", "suv"),
      m("Sentra", "sedan"),
      m("X-Trail", "suv"),
    ],
  },
  {
    name: "Opel",
    models: [
      m("Astra", "hatchback"),
      m("Combo", "van"),
      m("Corsa", "hatchback"),
      m("Crossland", "suv"),
      m("Grandland", "suv"),
      m("Insignia", "sedan"),
      m("Mokka", "suv"),
      m("Zafira", "van"),
    ],
  },
  {
    name: "Peugeot",
    models: [
      m("107", "mini"),
      m("2008", "suv"),
      m("208", "hatchback"),
      m("3008", "suv"),
      m("308", "hatchback"),
      m("408", "sedan"),
      m("5008", "suv"),
      m("508", "sedan"),
      m("Partner", "van"),
    ],
  },
  {
    name: "Renault",
    models: [
      m("Arkana", "suv"),
      m("Austral", "suv"),
      m("Captur", "suv"),
      m("Clio", "hatchback"),
      m("Kadjar", "suv"),
      m("Koleos", "suv"),
      m("Megane", "hatchback"),
      m("Megane E-Tech", "hatchback"),
      m("Scenic", "van"),
      m("Zoe", "hatchback"),
    ],
  },
  {
    name: "Seat",
    aliases: ["seat"],
    models: [
      m("Alhambra", "van"),
      m("Arona", "suv"),
      m("Ateca", "suv"),
      m("Ibiza", "hatchback"),
      m("Leon", "hatchback"),
      m("Mii", "mini"),
      m("Tarraco", "suv"),
      m("Toledo", "sedan"),
    ],
  },
  {
    name: "Skoda",
    aliases: ["škoda", "skoda"],
    models: [
      m("Enyaq", "suv"),
      m("Fabia", "hatchback"),
      m("Kamiq", "suv"),
      m("Karoq", "suv"),
      m("Kodiaq", "suv"),
      m("Octavia", "sedan"),
      m("Rapid", "sedan"),
      m("Scala", "hatchback"),
      m("Superb", "sedan"),
      m("Yeti", "suv"),
    ],
  },
  {
    name: "Subaru",
    models: [
      m("BRZ", "other"),
      m("Crosstrek", "suv"),
      m("Forester", "suv"),
      m("Impreza", "sedan"),
      m("Legacy", "sedan"),
      m("Outback", "suv"),
      m("XV", "suv"),
    ],
  },
  {
    name: "Suzuki",
    models: [
      m("Across", "suv"),
      m("Alto", "mini"),
      m("Baleno", "hatchback"),
      m("Celerio", "mini"),
      m("Ignis", "suv"),
      m("Jimny", "suv"),
      m("S-Cross", "suv"),
      m("Swift", "hatchback"),
      m("SX4", "suv"),
      m("Vitara", "suv"),
    ],
  },
  {
    name: "Tesla",
    models: [
      m("Cybertruck", "pickup"),
      m("Model 3", "sedan"),
      m("Model S", "sedan"),
      m("Model X", "suv"),
      m("Model Y", "suv"),
    ],
  },
  {
    name: "Toyota",
    models: [
      m("Auris", "hatchback"),
      m("Aygo", "mini"),
      m("bZ4X", "suv"),
      m("C-HR", "suv"),
      m("Camry", "sedan"),
      m("Corolla", "sedan"),
      m("Corolla Cross", "suv"),
      m("Highlander", "suv"),
      m("Hilux", "pickup"),
      m("Land Cruiser", "suv"),
      m("Prius", "hatchback"),
      m("RAV4", "suv"),
      m("Yaris", "hatchback"),
      m("Yaris Cross", "suv"),
    ],
  },
  {
    name: "Volkswagen",
    aliases: ["vw", "volkswagen", "volks wagen"],
    models: [
      m("Arteon", "sedan"),
      m("Caddy", "van"),
      m("Golf", "hatchback"),
      m("ID.3", "hatchback"),
      m("ID.4", "suv"),
      m("ID.Buzz", "van"),
      m("Jetta", "sedan"),
      m("Passat", "sedan"),
      m("Polo", "hatchback"),
      m("T-Cross", "suv"),
      m("T-Roc", "suv"),
      m("Tiguan", "suv"),
      m("Touareg", "suv"),
      m("Transporter", "van"),
    ],
  },
  {
    name: "Volvo",
    models: [
      m("C40", "suv"),
      m("EX30", "suv"),
      m("EX90", "suv"),
      m("S60", "sedan"),
      m("S90", "sedan"),
      m("V60", "sedan"),
      m("V90", "sedan"),
      m("XC40", "suv"),
      m("XC60", "suv"),
      m("XC90", "suv"),
    ],
  },
];
