/**
 * Local MVP vehicle catalog for Israel-common manufacturers and models.
 *
 * Stored `vehicle_make` / `vehicle_model` values should use `name` / `models`
 * strings exactly when a confident match exists. This module is data-only so
 * it can later be replaced by a Ministry of Transport or other canonical
 * source without changing the form UI.
 */
export type VehicleCatalogMake = {
  name: string;
  aliases?: readonly string[];
  models: readonly string[];
};

export const VEHICLE_CATALOG: readonly VehicleCatalogMake[] = [
  {
    name: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "Q4 e-tron",
      "Q6 e-tron",
      "e-tron",
      "e-tron GT",
      "TT",
    ],
  },
  {
    name: "BMW",
    aliases: ["bmw"],
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "7 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "i4",
      "i5",
      "i7",
      "iX",
      "iX1",
      "iX3",
      "XM",
    ],
  },
  {
    name: "BYD",
    models: ["Atto 2", "Atto 3", "Dolphin", "Han", "Seal", "Seal U", "Sealion 7", "Tang"],
  },
  {
    name: "Chevrolet",
    aliases: ["chevy"],
    models: [
      "Aveo",
      "Camaro",
      "Captiva",
      "Cruze",
      "Equinox",
      "Orlando",
      "Spark",
      "Traverse",
      "Trax",
    ],
  },
  {
    name: "Citroen",
    aliases: ["citroën", "citroen"],
    models: [
      "Berlingo",
      "C1",
      "C3",
      "C3 Aircross",
      "C4",
      "C4 Cactus",
      "C4 X",
      "C5 Aircross",
      "C5 X",
    ],
  },
  {
    name: "Cupra",
    models: ["Ateca", "Born", "Formentor", "Leon", "Tavascan", "Terramar"],
  },
  {
    name: "Dacia",
    models: ["Duster", "Jogger", "Logan", "Lodgy", "Sandero", "Spring"],
  },
  {
    name: "Fiat",
    models: ["500", "500e", "500X", "Doblo", "Ducato", "Panda", "Punto", "Tipo"],
  },
  {
    name: "Ford",
    models: [
      "EcoSport",
      "Explorer",
      "Fiesta",
      "Focus",
      "Kuga",
      "Mach-E",
      "Mondeo",
      "Mustang",
      "Puma",
      "Ranger",
      "Transit",
    ],
  },
  {
    name: "Geely",
    models: ["Coolray", "EX5", "Geometry C", "Okavango", "Starray"],
  },
  {
    name: "Honda",
    models: ["Accord", "Civic", "City", "CR-V", "e:Ny1", "HR-V", "Jazz"],
  },
  {
    name: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Getz",
      "i10",
      "i20",
      "i30",
      "i35",
      "Ioniq",
      "Ioniq 5",
      "Ioniq 6",
      "Kona",
      "Palisade",
      "Santa Fe",
      "Tucson",
      "Venue",
    ],
  },
  {
    name: "Kia",
    models: [
      "Carnival",
      "Ceed",
      "EV6",
      "EV9",
      "Niro",
      "Optima",
      "Picanto",
      "Rio",
      "Seltos",
      "Sorento",
      "Soul",
      "Sportage",
      "Stonic",
      "Telluride",
      "XCeed",
    ],
  },
  {
    name: "Lexus",
    models: ["ES", "IS", "LBX", "LS", "LX", "NX", "RX", "RZ", "UX", "UX 300e"],
  },
  {
    name: "MG",
    models: ["HS", "Marvel R", "MG3", "MG4", "MG5", "ZS"],
  },
  {
    name: "Mazda",
    models: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-90", "MX-5"],
  },
  {
    name: "Mercedes-Benz",
    aliases: ["mercedes", "mercedes benz", "mercedes-benz", "merc"],
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "CLA",
      "CLE",
      "CLS",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQS",
      "G-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "S-Class",
      "Sprinter",
      "Vito",
    ],
  },
  {
    name: "Mitsubishi",
    models: [
      "ASX",
      "Attrage",
      "Colt",
      "Eclipse Cross",
      "L200",
      "Lancer",
      "Outlander",
      "Pajero",
      "Space Star",
    ],
  },
  {
    name: "Nissan",
    models: [
      "Ariya",
      "Juke",
      "Leaf",
      "Micra",
      "Navara",
      "Note",
      "Pulsar",
      "Qashqai",
      "Sentra",
      "X-Trail",
    ],
  },
  {
    name: "Opel",
    models: ["Astra", "Combo", "Corsa", "Crossland", "Grandland", "Insignia", "Mokka", "Zafira"],
  },
  {
    name: "Peugeot",
    models: ["107", "2008", "208", "3008", "308", "408", "5008", "508", "Partner"],
  },
  {
    name: "Renault",
    models: [
      "Arkana",
      "Austral",
      "Captur",
      "Clio",
      "Kadjar",
      "Koleos",
      "Megane",
      "Megane E-Tech",
      "Scenic",
      "Zoe",
    ],
  },
  {
    name: "Seat",
    aliases: ["seat"],
    models: ["Alhambra", "Arona", "Ateca", "Ibiza", "Leon", "Mii", "Tarraco", "Toledo"],
  },
  {
    name: "Skoda",
    aliases: ["škoda", "skoda"],
    models: [
      "Enyaq",
      "Fabia",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Rapid",
      "Scala",
      "Superb",
      "Yeti",
    ],
  },
  {
    name: "Subaru",
    models: ["BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "XV"],
  },
  {
    name: "Suzuki",
    models: [
      "Across",
      "Alto",
      "Baleno",
      "Celerio",
      "Ignis",
      "Jimny",
      "S-Cross",
      "Swift",
      "SX4",
      "Vitara",
    ],
  },
  {
    name: "Tesla",
    models: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  },
  {
    name: "Toyota",
    models: [
      "Auris",
      "Aygo",
      "bZ4X",
      "C-HR",
      "Camry",
      "Corolla",
      "Corolla Cross",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "Prius",
      "RAV4",
      "Yaris",
      "Yaris Cross",
    ],
  },
  {
    name: "Volkswagen",
    aliases: ["vw", "volkswagen", "volks wagen"],
    models: [
      "Arteon",
      "Caddy",
      "Golf",
      "ID.3",
      "ID.4",
      "ID.Buzz",
      "Jetta",
      "Passat",
      "Polo",
      "T-Cross",
      "T-Roc",
      "Tiguan",
      "Touareg",
      "Transporter",
    ],
  },
  {
    name: "Volvo",
    models: ["C40", "EX30", "EX90", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
  },
];
